import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { describe, it } from 'node:test';

describe('Service Worker', () => {
  const swPath = 'dist/sw.js';
  let sw = '';

  it('is generated by the build', () => {
    assert.ok(existsSync(swPath), 'sw.js not found — run npm run build first');
    sw = readFileSync(swPath, 'utf-8');
  });

  it('precaches /index.html for navigation requests', () => {
    assert.ok(
      sw.includes('"/index.html"'),
      'PRECACHE_URLS must include /index.html',
    );
  });

  it('resolves navigation via /index.html with network fallback', () => {
    const pattern = `caches.match('/index.html').then(r=>r||fetch(e.request)`;
    assert.ok(
      sw.includes(pattern),
      'navigation fetch handler must match /index.html with network fallback',
    );
  });

  it('has network fallback for non-navigation requests', () => {
    assert.ok(
      sw.includes('caches.match(e.request).then(r=>r||fetch(e.request))'),
    );
  });

  it('activates immediately via skipWaiting', () => {
    assert.ok(sw.includes('self.skipWaiting()'));
  });

  it('takes control via clientsClaim', () => {
    assert.ok(sw.includes('self.clientsClaim()'));
  });

  it('contains a cache key derived from all asset filenames', () => {
    assert.ok(
      /PRECACHE='workingdiary-v[a-f0-9]{8}'/.test(sw),
      'cache key must contain 8-char hex hash',
    );
  });

  it('cache key changes when any asset file changes, not just CSS', () => {
    const keyMatch = sw.match(/PRECACHE='([^']+)'/);
    assert.ok(keyMatch);
    const actualKey = keyMatch[1];

    const urlsMatch = sw.match(/PRECACHE_URLS=\[(.*?)\]/);
    assert.ok(urlsMatch);
    const urls = JSON.parse(`[${urlsMatch[1]}]`) as string[];
    assert.ok(urls.length > 0);

    const sorted = [...urls].sort();
    const expectedKey = `workingdiary-v${createHash('sha256').update(sorted.join('|')).digest('hex').slice(0, 8)}`;

    assert.strictEqual(actualKey, expectedKey);
  });
});
